# version: '3.5'

# services:
#   database:
#     image: mysql:latest
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: persondb
#       MYSQL_USER: user
#       MYSQL_PASSWORD: 1234
#       #MYSQL_ALLOW_EMPTY_PASSWORD: true
#     ports:
#       - 3306:3306
#     expose:
#       - 3306
#     volumes:
#       - ./Database:/docker-entrypoint-initdb.d/
    
#   backendservice:
#     image: backendservice
#     container_name: backendservice
#     build:
#       context:
#         ./backend
#     depends_on:
#       - database
#     expose:
#       - 5000
#     networks:
#     - network1
#     - network2   
   
#   webserver:
#     container_name: webserver
#     build: ./proxy
#     restart: on-failure
#     ports:
#       - 80:80
#       - 443:443
#     depends_on:
#       - backendservice
#     networks:
#       - network1

# networks:
#   network1:
#     driver: bridge
#   network2:
#     driver: bridge  

version: '3.5'

services: 
    Database:
        image: mysql:latest
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: persondb
            MYSQL_USER: user
            MYSQL_PASSWORD: 1234
        expose: 
          - 3306
        networks:
          - network2
        volumes: 
            - ./Database/:/docker-entrypoint-initdb.d
    
    backend:
      image: backend
      container_name: backend
      build:
        context:
            ./backend
      depends_on:
          - Database
      expose:
        - 5000
      networks:
          - network1
          - network2
    
    proxy:
      image: nginx:latest
      volumes:
        - ./proxy/html:/usr/share/nginx/html
        - ./proxy/nginx.conf:/etc/nginx/nginx.conf
        - ./proxy/certificates:/etc/nginx/ssl
      ports:
        - 80:80
        - 443:443
      depends_on:
        - backend
      networks:
        - network1

networks:
  network1:
    driver: bridge
  network2:
    driver: bridge