version: '3.5'

services: 
    mysqldb:
        image: gitlab.sdu.dk:5050/odw-e2020/docker:mysql-latest
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: persondb
            MYSQL_USER: user
            MYSQL_PASSWORD: sql
        expose: 
          - 3306
        networks:
          - network2
        volumes: 
            - ./Database/:/docker-entrypoint-initdb.d
    
    backendserver:
      image: backend
      container_name: backend
      build:
        context:
            ./backend
      depends_on:
          - mysqldb
      expose:
        - 5000
      networks:
          - network1
          - network2
    
    proxy:
      image: gitlab.sdu.dk:5050/odw-e2020/docker:nginx-latest
      volumes:
        - ./proxy/html:/usr/share/nginx/html
        - ./proxy/nginx.conf:/etc/nginx/nginx.conf
        - ./proxy/certificates:/etc/nginx/ssl
      ports:
        - 80:80
        - 443:443
      depends_on:
        - backendserver
      networks:
        - network1

networks:
  network1:
    driver: bridge
  network2:
    driver: bridge