CREATE TABLE Person (
    PersonID int UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL
);

INSERT INTO Person VALUES (1,'John','Doe');
INSERT INTO Perso VALUES (2,'Art','Vandelay');