CREATE TABLE Person (
    PersonID int UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL
);

INSERT INTO Person VALUES (1,'John','Doe');
INSERT INTO Person VALUES (2,'Art','Vandelay');
INSERT INTO Person VALUES (3,'Jane','Doe');